# Avoid warnings about unrecognized runner types.
self-hosted-runner:
  labels:
    - linux-amd64-*
    - linux-arm64-*

# Avoid warnings about referencing things in ${{ vars.* }} statements.
config-variables:
  - AWS_REGION
  - AWS_ROLE_ARN
  - TELEMETRY_ENABLED

paths:
  .github/workflows/conda-python-tests.yaml:
    ignore:
      # ${{ secrets.CODECOV_TOKEN }} is valid if a secret like that exists in the calling repo,
      # and we're confident that it's there in our repos, so this error can be silenced
      - 'property "codecov_token" is not defined in object type'
