rules:
  unpinned-uses:
    config:
      policies:
        # We require SHA-pinning for all workflows and actions _except_ for those from
        # known NVIDIA-controlled repos
        "nv-gha-runners/*": ref-pin
        "rapidsai/shared-workflows/*": ref-pin
        "rapidsai/shared-actions/*": ref-pin
        "*": hash-pin
