name: Dispatch Prepare Build Matrix
description: Check out the shared-workflows repository and run the prepare-matrix action.

inputs:
  action-repo:
    description: Action repo.
    required: true
  action-ref:
    description: Action ref.
    required: true

outputs:
  matrix:
    description: Build matrix.
    value: ${{ steps.prepare-matrix.outputs.matrix }}

runs:
  using: composite
  steps:
    - name: Check out shared-workflows implementation
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        repository: ${{ inputs.action-repo || 'rapidsai/shared-workflows' }}
        ref: ${{ inputs.action-ref || 'main' }}
        path: ./shared-workflows
        persist-credentials: false
    - id: prepare-matrix
      name: Prepare Build Matrix
      uses: ./shared-workflows/.github/actions/prepare-matrix
