on:
  workflow_call:
    outputs:
      package-version-suffix:
        description: "Suffix to be appended to conda/sdist/wheel version numbers."
        value: ${{ jobs.build.outputs.version-suffix }}

permissions: {}

jobs:
  build:
    runs-on: ubuntu-slim
    outputs:
      version-suffix: ${{ steps.build-details.outputs.version-suffix }}
    steps:
      - name: build
        id: build-details
        run: |
          echo "version-suffix=.post$(date -u +'%y%m%d%H%M%S')" | tee -a "${GITHUB_OUTPUT}"
