on:
  workflow_call:
    outputs:
      build-datetime:
        description: "integer-formatted 'UTC now' datetime"
        value: ${{ jobs.build.outputs.build-datetime }}

permissions: {}

jobs:
  build:
    runs-on: ubuntu-slim
    outputs:
      build-datetime: ${{ steps.build-details.outputs.build-datetime }}
    steps:
      - name: build
        id: build-details
        run: |
          BUILD_DATETIME="$(date -u +'%y%m%d%H%M%S')"
          echo "build-datetime=${BUILD_DATETIME}" | tee -a "${GITHUB_OUTPUT}"
